"""init the db

Revision ID: 872d8cf66f53
Revises: 
Create Date: 2024-02-09 12:45:16.892612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872d8cf66f53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('amount_of_pln', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_symbol', sa.String(length=3), nullable=True),
    sa.Column('currency_name', sa.String(length=30), nullable=True),
    sa.Column('currency_amount', sa.Integer(), nullable=True),
    sa.Column('currency_price', sa.Integer(), nullable=True),
    sa.Column('date_of_action', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_symbol', sa.String(length=3), nullable=True),
    sa.Column('currency_amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    op.drop_table('history')
    op.drop_table('user')
    # ### end Alembic commands ###
